//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul._app_._TEST_.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a1")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>asf</string>\r\n  <string>asf</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Setting1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Setting1"]));
            }
            set {
                this["Setting1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,Reception")]
        public global::nilnul.app._run._cfg._entry.typ_.custom_.Room room {
            get {
                return ((global::nilnul.app._run._cfg._entry.typ_.custom_.Room)(this["room"]));
            }
            set {
                this["room"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::nilnul.app._run._cfg._entry.typ_.custom_.Employee exmployee {
            get {
                return ((global::nilnul.app._run._cfg._entry.typ_.custom_.Employee)(this["exmployee"]));
            }
            set {
                this["exmployee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::nilnul._app_._TEST_._run._cfg._entry.typ_.Custom typeInSameLibCanBeKeyedInManually {
            get {
                return ((global::nilnul._app_._TEST_._run._cfg._entry.typ_.Custom)(this["typeInSameLibCanBeKeyedInManually"]));
            }
            set {
                this["typeInSameLibCanBeKeyedInManually"] = value;
            }
        }
    }
}
